language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: NiaHk4ykzW6Y2VUiInMo54cwNI+VXrbomesNqvtU8tyz+SoLLZ4P2eT9x2cl1p+soiWx/XJFmIaPqe5qd6DWAxeHcB0eqhXKBYTK83hU2FzGCrQR8fgoG0H5Yra/h7xnFHBZpqNgryuP3yvTmgCYSWjl6FWFnw5QisDQ8YELJHGNBKPi8gOGQ34XsPI2M1zLWhnbTOPEu6zp88qblKbC2OqrreQaZVeGDPfsF1NYrTd0YuX4TjVjLeQTaK8oGoxxqvGJuac5KVIg9Qp909IQLU5LMTZ9FJT+O+FzN4qVZTI5LKBHKo3PBkK5xdtr69Wk37cjkymywUqSjaTwocTiGZ2BkG06jRQW8o16rmTc7XHkg/aIOsCzYbGJLw12Yd8Goh8Mcivqp0/y5/xmRBhUDzJsgEaqPJitFWJCc5fGWI7EyUkywEjcG89g+hgh+Jv7fHeP6lusoeJYzqjzTRyYWzFI5BxFmXx+lrE8qQtXJevwjGUd/03MeuFzySV50AoZHmWFyDdSwJTuYdGRdvMaVKhZWZXsWNc7fK1Cgvmn6yiqBCf61paeComFKSrzUcRwZL0dtLCV7TeEmVY6gFd/f8WRUvOtWDXImi1LRJ43JzgtlG+xiIRYmycEUau9hmEaATOabPV4iJW1sUKJmu82T3YxyGkY/iqObwWsjFq6IxA=
notifications:
  slack:
    secure: IHVUv24rzdXTIfdrIRXlK8uG4/7rvGMgvCTRhbk7e7U0OXGbQYNNUaPkXe8jXpo/RgJcqQCcMTOpbaw73YXBT0jPYpLzpIc/qlYSiW8pMtjKpwooDhxDjSoebmzYliCR7N5ux+YdXSSw0OQ/2u22XbEXM6E+u6+jzzCoaV1vUsh2qyPhOFlYzXKYmzPb4z5zX0KtjDYA1dbfj35oBFBqq4n8Afod3VjYQ1oYHvUD44yzNoCRuBRySWjF7IjvIH4JKwOeVdU9RYzR/qCR8a8juh+9RoDFkLmot61UnurJmuoTaq9ySWCGd/i+QRIk1QSj2xkOygMtNcFuVS9jOltUDSLiF22gE4drdeqfhMtBGC8hOgidrS96P1mb1lv8CR+Wr7shYt7FZoPdvyPuouGBA9T82+Uw+l7PLfCsgP0L3R8M4RBqASfdDOB0zmsKIdPc9UdSi8Yb2rIA51WZZ+FSCwxqpKRvg3GaH3YRA3YNDF6Q2qfsKyiEesTResPxVg6A6b8agmkpMDOLQZh9AoOVesZ7hqdDiHan1JP1UCQ1y35iA3kI1Wiu4wgwdlOOtD8M96xb3ysT3syXKrEqDcmWRPfVdpWLLBcaAVlOZXalQeq0xDdIh6aFiW+S14pTYdWZI0F7Ws7IwZrV6iYx0ycu1VBRjMfx2fH7KVyRqHM0RQw=
deploy:
- provider: npm
  api_key:
    secure: GaYC5TRpBRp0eSoX6TJ7aniaon5owBNAX96cWo0UgHO+hF3sYgpKkSJE+k4hbLhkPleMFO7YzT4poUVMlBbCMuVDcZllF6ldyChL7Ge83Tdstt8c39BxXO3Wn2nP1A7uDeKe4ssVc3HMRjel1WKxdYtEtwjOIDS+O/FsL3tqr1TaAKWLnoqcvgm5URV5NuUsYFjSmDRBNP5v/q8otqROFNGTEaYbRRkaFMaEhtDfZLi9uyx7VxJulfxTWbQtlU2F3tsMSZRpEv8aKEKHbJ5P7Av+mfyDM1nHoNJkgfjec4SSFGAvFR+spf9eiwoMEsNHJ0nJaWF/4ppDc7toKacTvAYncYoJqpAPsfjFcpssVWle4H6nT2sMH09RVZUNmHSDRkace3aKZGGK9vFcCqimbLXwq3L8c++McrZmpDF9GrNm4UkUbpzEqorT11G9iNXUM6gXa4nw5bA02crPkvXkRPGYI+Ve96rP16VS7ynyn499I5eJHia1kHEZpn7Uu11huq9XMfI1RK74tyF5Bds/yF9Vjru6AuQB013YDHGYBvQhT4m00QVeZnRAN+Kq7hRS/oOSxFT2w5s4aTU5QrYeoR1vnFSm4GSapNs++u9JRkriauHYFdqncAAXgdVifejPglU/T1pQWqhmhm3FeAbPJrRpMeyAQTcXlrQGfuVTHDg=
  email:
    secure: qcB9eeUOxIPwYp9kN9p1jpTcRmG5wmtFodMNNZk/BrDFt2wMaM5BGAzno0ylnzcYJoMp+OD+CbvLSqSMCd3/Xsy3eoZdjVHY2HipZgNdQRsaSGdMLZpghgv2n+6W3xcUilcKWj3mqigpSrSvu/I9eLW4wJQv6OhuiUgAnLCcMVLsOa0FQARI9BOaeQH43q1GvUCFiaMLLsKBzRYJKtnF+bnyeJBa+C7MKs3eiS5QAHzhTu6LdR/PYEexGZ1Iwaquh8v1H2s1pIaaOHvRhBCFrTpCh7hRcrm4uqVhReDjrh2FiID3GpqybLFUElhTCNuXy9ivlyhs7qzKbAN2XhzoHl7MzSKMtRspr3TdEC0PSuV6ZbfJ64yTe0Y33YqIgP7xp1lgKh5HZlCFxeX1tGo8y90VzbkLKn6pZk+SYt7kEsFHzigH1hlbhqhAOk4gMl9amJz/mBDTjx+VDRXigFrvYh+bo45ud2pSzLntye/q8qDXWP80tTbjGBxINddX0YrL+7ozSiB3PVY9ZX1xDSzoeYKZGvVwbrzGWmOwS025wZk4Usjsc6nHdTaAUTKAfJ7H9rPlULyyXlXdZSpUv7XeLt6IrvExnNSpelLWEufyJ7f3bogBQFwf+w3O1uouUZGikq0xpHVXmS0YQs43W1xww6AVxQ1dysGe/BUYL8AyZ84=
  on:
    branch: master
